[XDebug]
zend_extension=xdebug.so

xdebug.mode=debug
;xdebug.mode=debug,profile
xdebug.client_host=172.17.0.1
xdebug.client_port=9003
xdebug.idekey=PHPSTORM
xdebug.discover_client_host=1
xdebug.start_with_request=yes
xdebug.output_dir=/srv/app/storage/profiler
xdebug.profiler_output_dir=/srv/app/storage/profiler
#xdebug.log="/srv/app/storage/xdebug.log"
xdebug.remote_autostart=1
xdebug.remote_mode=req
xdebug.remote_enable=1
